use_frameworks!

target 'Example' do
  pod 'sdk_ios_v2', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end

